apiVersion: v1
kind: PersistentVolume
metadata:
  name: edge
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/vertx/edge
    server: 10.19.137.41
  persistentVolumeReclaimPolicy: Recycle
