service:
  airports:
    baseUrl: http://edge:8080/airports
  flights:
    baseUrl: http://edge:8080/flights
  sales:
    baseUrl: http://edge:8080/sales

pricing:
  pool:
    size: 20
  failure:
    max: 50
    timeout: 5000
    fallback: true
    reset: 30000

JAEGER_AGENT_HOST: jaeger-agent
JAEGER_AGENT_PORT: 6831
JAEGER_SERVICE_NAME: presentation
JAEGER_REPORTER_LOG_SPANS: true
JAEGER_SAMPLER_TYPE: const
JAEGER_SAMPLER_PARAM: 1
